### PR TITLE
Update drawer.vim

### PR DESCRIPTION
**Pull request by chana1024**
add function db_ui#drawer#get()

### CODE REVIEW

**Comment by chana1024** [comment]
get drawer instance in other vim file

**Comment by kristijanhusak** [comment]
I'm curious why you need this?

**Comment by chana1024** [comment]
> I'm curious why you need this?

image
i want to add some feature for myself  and don't change your code

**Comment by chana1024** [comment]
> I'm curious why you need this?
image
i want to add some feature for myself and don't change your code

**Comment by chana1024** [comment]
> I'm curious why you need this?
Screenshot 2021-11-19 165801
i want to add some feature for myself and don't change your code

**Pull request merged**
