### PR TITLE
leverage dotenv.vim and a prefix in .env files

### PR DESCRIPTION
**Pull request by skriems**
hey @kristijanhusak,

I got my hands dirty with vimscript and that's the approach I mentioned in #4. Sry that I have no test at hand - first time vimscript 😄 

I iterate over all env variables which already were read by `dotenv.vim` and use a prefix to determine the ones I'm interested in. As far as I can tell, this code should be safe without dotenv, since I'm ending up with an empty dict in this case.

This way the user can specify an arbitrary amount of connections in an `.env` file and customize the prefix you want to use.

What do you think? :)

As a sideeffect/bug it seems that `dotenv.vim` is loaded after `dadbod-ui` got loaded (maybe because of alphabetical order?), so at the time we're trying to get the env variables `dotenv` is not loaded yet. Hence no connections from env. I have to reload the buffer or open up another one before opening the UI

### CODE REVIEW

**Comment by skriems** [comment]
_checking the tests_

**Comment by kristijanhusak** [comment]
Tests are failing because you changed the old functionality.

This is ok, but the problem is that it's limited to dotenv. Older functionality allowed reading any environment variable that is not tied to dotenv.

Let's leave the old functionality, and add this one separately.
Rename `g:db_ui_env_variable_prefix` to `g:db_ui_dotenv_variable_prefix` and add a separate function to handle those variables.

**Comment by skriems** [comment]
done @kristijanhusak

**Comment by kristijanhusak** [comment]
Looks good. Only issue i can for-see is that both env implementation start with same prefix, which can potentially cause conflicts. Lets use `DB_UI` for this dotenv prefix just to make it different by default.

**Comment by skriems** [comment]
good point. I renamed it to `DB_UI_` leaving the underscore which I think makes it clearer to be a prefix

**Comment by kristijanhusak** [comment]
Just please update the readme also.

**Comment by skriems** [comment]
sure 🙈 should be good now

**Comment by kristijanhusak** [comment]
Looks good, thanks!

**Pull request merged**
