### PR TITLE
Add support for vim-dadbod BiqQuery adapter

### PR DESCRIPTION
**Pull request by mbhynes**
## Summary

- This PR adds support for BigQuery, an OLAP database provided by Google
- It depends on an upstream PR https://github.com/tpope/vim-dadbod/pull/125 in the `vim-dadbod` repo

### Example Screenshot
vim-dadbod-ui2

### CODE REVIEW

**Comment by mbhynes** [comment]
@kristijanhusak Sorry for the double PRs! I opened up https://github.com/kristijanhusak/vim-dadbod-ui/pull/159 as a draft but have made some other edits since. I'll close the other one.

Thank you for your [question here](https://github.com/kristijanhusak/vim-dadbod-ui/pull/159#discussion_r1119665419) however; I've replied in that review thread and would appreciate your suggestions 🙏

**Comment by mbhynes** [comment]
Hi @kristijanhusak,

I've just updated this feature branch to add in a global variable `g:db_adapter_bigquery_region`, to allow users to parameterize the schema query:

```vim
if !exists('g:db_adapter_bigquery_region')
  let g:db_adapter_bigquery_region = 'region-us'
endif

let s:bigquery_schemas_query = "SELECT schema_name FROM INFORMATION_SCHEMA.SCHEMATA"

let s:bigquery_schema_tables_query = printf("
      \ SELECT table_schema, table_name
      \ FROM `%s`.INFORMATION_SCHEMA.TABLES
      \ ", g:db_adapter_bigquery_region)
```

Would you please lmk if that's acceptable for removing the hardcoded `region-us`?

**Comment by magal1337** [comment]
hey @mbhynes congrats for this PR! Very excited to finally run my Data Engineer queries for BigQuery inside Vim! One question how we can add new schemas using the command line? Another thing I tried to ran a query but the output is only giving me the number of lines.
image

**Comment by mbhynes** [comment]
> hey @mbhynes congrats for this PR! Very excited to finally run my Data Engineer queries for BigQuery inside Vim! One question how we can add new schemas using the command line? Another thing I tried to ran a query but the output is only giving me the number of lines.
> I tried press U inside Schemas flag but I'm receiving: "Cannot make changes, 'modifiable' is off"
> image
> 

Hiya thanks for trying this out! When I last ran this a few weeks ago I also had the modifiable buffer issue, so I think there's likely an issue that I need to address after rebasing. I'm still waiting on landing the upstream PR tho and haven't been updating this PR as that one has been WIP. I'll take another look when the upstream is merged and fix this one, thanks for your feedback and patience🙏

**Comment by mbhynes** [comment]
> hey @mbhynes congrats for this PR! Very excited to finally run my Data Engineer queries for BigQuery inside Vim! One question how we can add new schemas using the command line? Another thing I tried to ran a query but the output is only giving me the number of lines. I tried press U inside Schemas flag but I'm receiving: "Cannot make changes, 'modifiable' is off" image

Hi @magal1337, this was resolved on my end after rebasing; this PR was closed when I synced the fork but I've opened up https://github.com/kristijanhusak/vim-dadbod-ui/pull/207

**Pull request closed without merging**
