### PR TITLE
Update list of SQL Server helpers

### PR DESCRIPTION
**Pull request by pnetherwood**
Add additional helpers for SQL Server:
- Columns: Column summary with keys, datatypes and nullable
- Indexes: Show table indexes using sp_helpindex
- Primary Keys: Same as Postgress helpers
- References: Same as Postgress helpers
- Foreign Keys: Same as Postgress helpers
- Describe: Show full table information using sp_help

### CODE REVIEW

**Comment by pnetherwood** [comment]
I've added additional helpers for sql server and tested them on our databases. The "Columns" one is a little different than your others as it creates a summary view rather than a raw table view. The output for one of my tables for example is:

```
Columns                                                                                                                                                                                                                                                                                                                                             
-------------
Execution_ID (PK, int(10,0), not null)                                                                                                                                                                                                                                                                                                              
MarketOrder_ID (FK, int(10,0), null)                                                                                                                                                                                                                                                                                                                
ticketNumber (FK, int(10,0), null)                                                                                                                                                                                                                                                                                                                  
claimTime (datetime2(7), null)                                                                                                                                                                                                                                                                                                                      
split (decimal(19,4), null)                                                                                                                                                                                                                                                                                                                         
marketTraded (varchar(9), null)                                                                                                                                                                                                                                                                                                                     
primeBrokerCode (FK, varchar(4), null)                                                                                                                                                                                                                                                                                                              
brokerCode (FK, varchar(4), null)                                                                                                                                                                                                                                                                                                                   
comment (varchar(80), null)                                                                                                                                                                                                                                                                                                                         
mic (char(4), null)
```

It mirrors what the column view is in SQL Server Manager. I find it quite useful to see a full column view without having to scroll around.

The full column view is shown in Describe which calls `sp_help` which is pretty much the same as `descr` in MySql.

The Constraints helper also show the full constraint code if available e.g.:

```
CONSTRAINT_NAME                                                                                                                  CHECK_CLAUSE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
-------------------------------------------------------------------------------------------------------------------------------- ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
CC_LIQUIDITY_FACTOR                                                                                                              ([liquidityFactor]>=(0))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
CC_SPOT_LIMIT                                                                                                                    ([spotlimit] IS NULL AND [spotdate] IS NULL OR [spotlimit] IS NOT NULL AND [spotdate] IS NOT NULL)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
CC_TYPE_FND_LTD                                                                                                                  (([type]='F' OR [type]='S') AND ([firstNoticeDay] IS NOT NULL OR [lastTradingDay] IS NOT NULL) OR [type]='P' OR [type]='X' OR [type]='C')                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       

```

**Comment by kristijanhusak** [comment]
Looks good, thanks!

**Comment by kristijanhusak** [comment]
@pnetherwood are you sure Foreign key query is same as Postgres? I'm getting wrong results:
For this foreign key added:
```sql
ALTER Table Posts ADD CONSTRAINT FK_PersonID FOREIGN KEY (PersonID)
REFERENCES Persons(ID) ON DELETE CASCADE ON UPDATE CASCADE
```
I get these results:
```
constraint_name table_name column_name foreign_table_name foreign_column_name 
--------------- ---------- ----------- ------------------ -------------------
FK_PersonID     Posts      PersonID    Posts              PersonID 
```

Foreign table name and foreign column name should be Persons and ID

**Comment by pnetherwood** [comment]
I'll double check. When you say you're getting wrong results are you doing
it on Postgress or Sql Server?

**Comment by kristijanhusak** [comment]
Sql server. Postgres returns proper results.

**Pull request merged**
