### PR TITLE
update the doc for db_ui_show_databse_icon option

### PR DESCRIPTION
**Pull request by glepnir**
@kristijanhusak  Please check this doc. Thanks.

### CODE REVIEW

**Comment by kristijanhusak** [comment]
Thanks.

**Comment by kristijanhusak** [comment]
@glepnir I added a support for nerd fonts. add `let g:db_ui_use_nerd_fonts = 1` to your vimrc and check. You can also change it if you don't like it more easily.

**Comment by glepnir** [comment]
@kristijanhusak  Thanks. i wil look at it.  Does this icon support highlight?

**Comment by kristijanhusak** [comment]
@glepnir yeah, it has highlights.

**Comment by glepnir** [comment]
@kristijanhusak  ok! Thanks for your work.

**Pull request merged**
