### PR TITLE
Add quiet and new command DBUIToggle

### PR DESCRIPTION
**Pull request by glepnir**
1. add a new map q to quiet dbui buffer.
2. add a new command DBUIToggle to toggle dbui buffer

### CODE REVIEW

**Comment by glepnir** [comment]
aha ,seems like test not pass.

**Comment by kristijanhusak** [comment]
I added this myself. Thanks for PR.

**Comment by glepnir** [comment]
Ok.

**Comment by glepnir** [comment]
@kristijanhusak  I have a question, when first open vim, input `DBUIToggle` command, I will got `not an command`,but when i use `DBUI` command then the `DBUIToggle` command works.

**Comment by kristijanhusak** [comment]
@glepnir both commands are defined in same file, so that's hardly possible by default. Do you use Plug's `on` for dbui toggle maybe?

**Comment by glepnir** [comment]
@kristijanhusak  Thanks, I forget define the command `DBUIToggle` to load plugin.

**Pull request closed without merging**
